image:
  file: .gitpod.dockerybu
tasks:
  - name: run
    command: |
      yugabyted start --base_dir=$STORE --listen=$HOST_LB1
      gp await-port 5433
      ysqlsh
            
# exposed ports
ports:
  - port: 7001
    onOpen: notify
  - port: 7002
    onOpen: notify
  - port: 7003
    onOpen: notify
  - port: 8201
    onOpen: notify
  - port: 8202
    onOpen: notify
  - port: 8203
    onOpen: notify
  - port: 37843
    onOpen: ignore
  - port: 7100
    onOpen: ignore
  - port: 9100
    onOpen: ignore
  - port: 5433
    onOpen: notify
  - port: 13000
    onOpen: ignore
  - port: 9042
    onOpen: notify
  - port: 12000
    onOpen: ignore

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers