image:
  file: .gitpod.DockerFile
tasks:
  - name: run
    command: |
      yb-ctl --rf 3 create  \
      --data_dir $STORE \
      --tserver_flags "yb_num_shards_per_tserver=1,ysql_num_shards_per_tserver=1,ysql_beta_features=true,webserver_port=8200" \
      --master_flags "yb_num_shards_per_tserver=1,ysql_num_shards_per_tserver=1" \
      --num_shards_per_tserver 1  \
      --placement_info "azure.region1.zone1,azure.region1.zone2,azure.region1.zone3" 
      gp await-port 5433
      ysqlsh
ports:
  - port: 7000
    onOpen: notify
  - port: 8200
    onOpen: notify
  - port: 37843
    onOpen: ignore
  - port: 7100
    onOpen: ignore
  - port: 9000
    onOpen: ignore
  - port: 9001
    onOpen: ignore
  - port: 9002
    onOpen: ignore
  - port: 9003
    onOpen: ignore
  - port: 9004
    onOpen: ignore
  - port: 9005
    onOpen: ignore
  - port: 9100
    onOpen: ignore
  - port: 5433
    onOpen: notify
  - port: 13000
    onOpen: ignore
  - port: 9042
    onOpen: notify
  - port: 12000
    onOpen: ignore
vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
experimentalNetwork: true     